name: rbstreamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.0.1=pyhd8ed1ab_1
  - appnope=0.1.3=pyhd8ed1ab_0
  - astropy=5.3.1=py39h57e1da4_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - aws-c-auth=0.7.0=h1eac0a6_2
  - aws-c-cal=0.6.0=h865601d_0
  - aws-c-common=0.8.23=h0dc2134_0
  - aws-c-compression=0.2.17=hd42d803_1
  - aws-c-event-stream=0.3.1=h7dedc3b_1
  - aws-c-http=0.7.11=h3f765f7_0
  - aws-c-io=0.13.28=h8caa2fd_0
  - aws-c-mqtt=0.8.14=h81f52c0_2
  - aws-c-s3=0.3.13=h54f3bce_2
  - aws-c-sdkutils=0.1.11=hd42d803_1
  - aws-checksums=0.1.16=hd42d803_1
  - aws-crt-cpp=0.20.3=h9f4e08a_4
  - aws-sdk-cpp=1.10.57=h6c51782_17
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - boltons=23.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=hb7f2c08_9
  - brotli-bin=1.0.9=hb7f2c08_9
  - brotli-python=1.0.9=py39h7a8716b_9
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.19.1=h0dc2134_0
  - ca-certificates=2023.7.22=h8857fd0_0
  - cachetools=5.3.1=pyhd8ed1ab_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py39h131948b_3
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.6=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - conda=23.5.2=py39h6e9494a_0
  - conda-package-handling=2.0.2=pyh38be061_0
  - conda-package-streaming=0.8.0=pyhd8ed1ab_0
  - contourpy=1.1.0=py39h8ee36c8_0
  - cryptography=41.0.2=py39he8b0a07_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.7=py39h7a8716b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fonttools=4.41.1=py39hdc70f33_0
  - freetype=2.12.1=h3f81eb7_1
  - gflags=2.2.2=hb1e8313_1004
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.32=pyhd8ed1ab_0
  - glog=0.6.0=h8ac2a54_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib-resources=6.0.0=pyhd8ed1ab_1
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.0=pyhd8ed1ab_1
  - ipykernel=6.24.0=pyh5fb750a_0
  - ipython=8.14.0=pyhd1c38e8_0
  - ipywidgets=8.0.7=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.18.4=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py39h6e9494a_0
  - jupyterlab_widgets=3.0.8=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py39h92daf61_1
  - krb5=1.21.1=hb884880_0
  - lcms2=2.15=h2dcdeff_1
  - lerc=4.0.0=hb486fe8_0
  - libabseil=20230125.3=cxx17_h000cb23_0
  - libarrow=12.0.1=h8d37b20_5_cpu
  - libblas=3.9.0=17_osx64_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_9
  - libbrotlidec=1.0.9=hb7f2c08_9
  - libbrotlienc=1.0.9=hb7f2c08_9
  - libcblas=3.9.0=17_osx64_openblas
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.2.0=h5f667d7_0
  - libcxx=16.0.6=hd57cbcb_0
  - libdeflate=1.18=hac1461d_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libevent=2.1.12=ha90c15b_1
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=12_3_0_h97931a8_0
  - libgfortran5=12.3.0=hbd3c1fe_0
  - libgoogle-cloud=2.12.0=h37a168a_1
  - libgrpc=1.56.2=he6801ca_0
  - libjpeg-turbo=2.1.5.1=hb7f2c08_0
  - liblapack=3.9.0=17_osx64_openblas
  - libnghttp2=1.52.0=he2ab024_0
  - libopenblas=0.3.23=openmp_h429af6e_0
  - libpng=1.6.39=ha978bb4_0
  - libprotobuf=4.23.3=h5feb325_0
  - libsodium=1.0.18=hbcb3906_1
  - libsqlite=3.42.0=h58db7d2_0
  - libssh2=1.11.0=hd019ec5_0
  - libthrift=0.18.1=h88b220a_2
  - libtiff=4.5.1=hf955e92_0
  - libutf8proc=2.8.0=hb7f2c08_0
  - libwebp-base=1.3.1=h0dc2134_0
  - libxcb=1.15=hb7f2c08_0
  - libzlib=1.2.13=h8a1eda9_5
  - llvm-openmp=16.0.6=hff08bdf_0
  - lz4-c=1.9.4=hf0c8a7f_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py39hdc70f33_0
  - matplotlib=3.7.2=py39h6e9494a_0
  - matplotlib-base=3.7.2=py39h6e39af2_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=hf0c8a7f_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - numpy=1.25.1=py39h892e69a_0
  - openjpeg=2.5.0=h13ac156_2
  - openssl=3.1.1=h8a1eda9_1
  - orc=1.9.0=hef23039_1
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py39h11b3245_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py39he6683de_1
  - pip=23.2.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.9.1=pyhd8ed1ab_0
  - plotly=5.15.0=pyhd8ed1ab_0
  - pluggy=1.2.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - protobuf=4.23.3=py39hbbf3ace_0
  - psutil=5.9.5=py39ha30fb19_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=12.0.1=py39h8c09acb_5_cpu
  - pycosat=0.6.4=py39ha30fb19_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pydeck=0.8.0=pyhd8ed1ab_0
  - pyerfa=2.0.0.3=py39h7cc1f47_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pympler=1.0.1=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.16=h709bd14_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0=py39ha30fb19_5
  - pyzmq=25.1.0=py39hdac9eea_0
  - re2=2023.03.02=h096449b_0
  - readline=8.2=h9e318b2_1
  - referencing=0.30.0=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rich=13.4.2=pyhd8ed1ab_0
  - rpds-py=0.9.2=py39hf33989b_0
  - ruamel.yaml=0.17.32=py39hdc70f33_0
  - ruamel.yaml.clib=0.2.7=py39ha30fb19_1
  - scipy=1.11.1=py39hded996c_0
  - setuptools=68.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.10=h225ccf5_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - streamlit=1.24.1=pyhd8ed1ab_1
  - tenacity=8.2.2=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3.2=py39hdc70f33_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - tzlocal=3.0=py39h6e9494a_2
  - unicodedata2=15.0.0=py39ha30fb19_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - validators=0.20.0=pyhd8ed1ab_0
  - watchdog=3.0.0=py39h82e4197_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.41.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.8=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=h0dc2134_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zstandard=0.19.0=py39h5705987_2
  - zstd=1.5.2=h829000d_7
prefix: /Users/robertseaton/anaconda3/envs/rbstreamlit
